services:
  compound-interest-calculator:
    container_name: compound-interest-calculator
    build:
      context: .
      dockerfile: Dockerfile
    image: compound-interest-calculator:latest
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s